name: Run Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, ubuntu-latest, macos-latest]
    env:
      CIBW_BUILD: 'cp39-*'
      CIBW_ARCHS: 'auto64'
     
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4      

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install (MacOS) 
        if: runner.os == 'macOS'
        run: |
          brew install llvm libomp
          export CC=/usr/local/opt/llvm/bin/clang
          export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
          export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
          export LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
          python -m pip install cibuildwheel==2.16.5
          python -m cibuildwheel --output-dir wheelhouse
      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt install libomp-dev
          python -m pip install cibuildwheel==2.16.5
          python -m cibuildwheel --output-dir wheelhouse
      - name: Install (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m pip install cibuildwheel==2.16.5
          python -m cibuildwheel --output-dir wheelhouse
      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
      - name: Run Example
        run: |
          python -m pip install --no-index --find-links wheelhouse/ rat
          python examples/DSPC_custom_layers_example.py 
